services:
  backend:
    image: node:22-alpine
    volumes:
      - ./backend/:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev2"
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
    environment:
      PORT: ${NODE_APP_PORT:-3000}
  frontend:
    image: node:22-alpine
    volumes:
      - ./frontend/:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
  postgres:
    image: postgres:17
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-e-commerce}
      POSTGRES_USER: ${POSTGRES_USER:-e-commerce-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-e-commerce-password}
    ports:
      - 5433:5432